code --install-extension adpyke.codesnap
code --install-extension alexisvt.flutter-snippets
code --install-extension astro-build.astro-vscode
code --install-extension bierner.markdown-mermaid
code --install-extension dart-code.dart-code
code --install-extension dart-code.flutter
code --install-extension dbaeumer.vscode-eslint
code --install-extension donjayamanne.githistory
code --install-extension dsznajder.es7-react-js-snippets
code --install-extension eamodio.gitlens
code --install-extension editorconfig.editorconfig
code --install-extension esbenp.prettier-vscode
code --install-extension github.copilot
code --install-extension github.copilot-chat
code --install-extension intellsmi.comment-translate
code --install-extension jebbs.plantuml
code --install-extension jock.svg
code --install-extension marp-team.marp-vscode
code --install-extension ms-ceintl.vscode-language-pack-ja
code --install-extension ms-vsliveshare.vsliveshare
code --install-extension mthuong.vscode-flutter-freezed-helper
code --install-extension pkief.material-icon-theme
code --install-extension rangav.vscode-thunder-client
code --install-extension redhat.java
code --install-extension ritwickdey.liveserver
code --install-extension robert-brunhage.flutter-riverpod-snippets
code --install-extension rvest.vs-code-prettier-eslint
code --install-extension streetsidesoftware.code-spell-checker
code --install-extension svelte.svelte-vscode
code --install-extension toba.vsfire
code --install-extension tomoki1207.pdf
code --install-extension visualstudioexptteam.intellicode-api-usage-examples
code --install-extension visualstudioexptteam.vscodeintellicode
code --install-extension vscjava.vscode-gradle
code --install-extension vscjava.vscode-java-debug
code --install-extension vscjava.vscode-java-dependency
code --install-extension vscjava.vscode-java-pack
code --install-extension vscjava.vscode-java-test
code --install-extension vscjava.vscode-maven
code --install-extension vscode-icons-team.vscode-icons
code --install-extension vscodevim.vim
code --install-extension wayou.vscode-todo-highlight
code --install-extension withfig.fig
code --install-extension yzane.markdown-pdf
code --install-extension zenn.zenn-preview
