code --install-extension adpyke.codesnap@1.3.4
code --install-extension alexisvt.flutter-snippets@3.0.0
code --install-extension astro-build.astro-vscode@2.7.4
code --install-extension bierner.markdown-mermaid@1.22.0
code --install-extension dart-code.dart-code@3.82.0
code --install-extension dart-code.flutter@3.82.0
code --install-extension dbaeumer.vscode-eslint@2.4.4
code --install-extension donjayamanne.githistory@0.6.20
code --install-extension dsznajder.es7-react-js-snippets@4.4.3
code --install-extension eamodio.gitlens@14.8.2
code --install-extension editorconfig.editorconfig@0.16.4
code --install-extension esbenp.prettier-vscode@10.1.0
code --install-extension github.copilot@1.162.0
code --install-extension github.copilot-chat@0.12.2
code --install-extension intellsmi.comment-translate@2.3.3
code --install-extension jebbs.plantuml@2.17.5
code --install-extension jock.svg@1.5.3
code --install-extension marp-team.marp-vscode@2.8.0
code --install-extension ms-ceintl.vscode-language-pack-ja@1.85.2024021409
code --install-extension ms-vsliveshare.vsliveshare@1.0.5905
code --install-extension mthuong.vscode-flutter-freezed-helper@0.1.0
code --install-extension pkief.material-icon-theme@4.33.0
code --install-extension rangav.vscode-thunder-client@2.17.8
code --install-extension redhat.java@1.28.1
code --install-extension ritwickdey.liveserver@5.7.9
code --install-extension robert-brunhage.flutter-riverpod-snippets@1.2.2
code --install-extension rvest.vs-code-prettier-eslint@6.0.0
code --install-extension streetsidesoftware.code-spell-checker@3.0.1
code --install-extension svelte.svelte-vscode@108.2.2
code --install-extension toba.vsfire@1.4.1
code --install-extension tomoki1207.pdf@1.2.2
code --install-extension visualstudioexptteam.intellicode-api-usage-examples@0.2.8
code --install-extension visualstudioexptteam.vscodeintellicode@1.2.30
code --install-extension vscjava.vscode-gradle@3.13.5
code --install-extension vscjava.vscode-java-debug@0.56.0
code --install-extension vscjava.vscode-java-dependency@0.23.4
code --install-extension vscjava.vscode-java-pack@0.25.15
code --install-extension vscjava.vscode-java-test@0.40.1
code --install-extension vscjava.vscode-maven@0.44.0
code --install-extension vscode-icons-team.vscode-icons@12.7.0
code --install-extension vscodevim.vim@1.27.2
code --install-extension wayou.vscode-todo-highlight@1.0.5
code --install-extension withfig.fig@0.0.7
code --install-extension yzane.markdown-pdf@1.5.0
code --install-extension zenn.zenn-preview@0.1.4
