# desc: Flutter / Dart / Java / Xcode 周り (asdf の flutter、xcodes CLI、openjdk、bundletool、Android Studio)
tap "xcodesorg/made"
brew "openjdk" # JDK はこれだけ。/usr/libexec/java_home に見せるには install.sh の symlink
brew "bundletool"
cask "android-studio"
brew "xcodesorg/made/xcodes" # CLI。GUI 版 (cask xcodes-app) は使っていないので入れない。CLI と GUI が両方あるものは CLI に寄せる
